### ISSUE TITLE
Creating backup

### ISSUE THREAD

**Issue by Shalinpatel-Abbvie** [Nuix/Bulk-Case-Migration#1]
Hello, 

It appears that when I use this script and decide to create a backup, it takes way too long to create that back up. I understand this new migration script compresses the backup of the nuix case. I choose the value '0' so its faster, however for a 10gb nuix case, it took almost 12 hours to backup. Is there something we can do that's more efficient. We have about 5,000 Nuix cases to migrate, so I'm trying to find something that's quick.

**Comment by JuicyDragon** [comment]
Hello @Shalinpatel-Abbvie the alternatives I can think of:
- Don't do backups (probably not a good idea)
- Backup the cases by copying them, not currently supported by this script, but the older version backs up cases by making copies and can be found here: https://github.com/Nuix/Case-Migration-Script , you could also make the backup copies outside of either script which could potentially be the fastest?
- The script uses a different compression format, I'm not sure what different format that would be and the script would need to be updated to support whatever compression format was chosen

**Comment by Shalinpatel-Abbvie** [comment]
Thank you, I will use the older script. I have used it before, but I was sure if this new one could benefit my case.
